/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResolveRouteImport } from './routes/resolve'
import { Route as MyRouteImport } from './routes/my'
import { Route as MigrateRouteImport } from './routes/migrate'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DeactivateRouteImport } from './routes/deactivate'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as IndexRouteImport } from './routes/index'

const ResolveRoute = ResolveRouteImport.update({
  id: '/resolve',
  path: '/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateRoute = MigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeactivateRoute = DeactivateRouteImport.update({
  id: '/deactivate',
  path: '/deactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/docs': typeof DocsRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/resolve': typeof ResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/docs': typeof DocsRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/resolve': typeof ResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/docs': typeof DocsRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/resolve': typeof ResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/deactivate'
    | '/docs'
    | '/migrate'
    | '/my'
    | '/resolve'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claim' | '/deactivate' | '/docs' | '/migrate' | '/my' | '/resolve'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/deactivate'
    | '/docs'
    | '/migrate'
    | '/my'
    | '/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  DeactivateRoute: typeof DeactivateRoute
  DocsRoute: typeof DocsRoute
  MigrateRoute: typeof MigrateRoute
  MyRoute: typeof MyRoute
  ResolveRoute: typeof ResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resolve': {
      id: '/resolve'
      path: '/resolve'
      fullPath: '/resolve'
      preLoaderRoute: typeof ResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate': {
      id: '/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof MigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deactivate': {
      id: '/deactivate'
      path: '/deactivate'
      fullPath: '/deactivate'
      preLoaderRoute: typeof DeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  DeactivateRoute: DeactivateRoute,
  DocsRoute: DocsRoute,
  MigrateRoute: MigrateRoute,
  MyRoute: MyRoute,
  ResolveRoute: ResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
