/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as DeactivateRouteImport } from './routes/deactivate'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EditRouteImport } from './routes/edit'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as IssueRouteImport } from './routes/issue'
import { Route as MigrateRouteImport } from './routes/migrate'
import { Route as MyRouteImport } from './routes/my'
import { Route as ReputationRouteImport } from './routes/reputation'
import { Route as ResolveRouteImport } from './routes/resolve'
import { Route as RotateRouteImport } from './routes/rotate'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsCellModelRouteImport } from './routes/docs/cell-model'
import { Route as DocsDidCkbRouteImport } from './routes/docs/did-ckb'
import { Route as DocsMigrationRouteImport } from './routes/docs/migration'
import { Route as DocsResolutionRouteImport } from './routes/docs/resolution'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyDiscordRouteImport } from './routes/verify/discord'
import { Route as VerifyGithubRouteImport } from './routes/verify/github'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const DeactivateRoute = DeactivateRouteImport.update({
  id: '/deactivate',
  path: '/deactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueRoute = IssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateRoute = MigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ReputationRoute = ReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolveRoute = ResolveRouteImport.update({
  id: '/resolve',
  path: '/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const RotateRoute = RotateRouteImport.update({
  id: '/rotate',
  path: '/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCellModelRoute = DocsCellModelRouteImport.update({
  id: '/cell-model',
  path: '/cell-model',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDidCkbRoute = DocsDidCkbRouteImport.update({
  id: '/did-ckb',
  path: '/did-ckb',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMigrationRoute = DocsMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResolutionRoute = DocsResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => DocsRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDiscordRoute = VerifyDiscordRouteImport.update({
  id: '/verify/discord',
  path: '/verify/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyGithubRoute = VerifyGithubRouteImport.update({
  id: '/verify/github',
  path: '/verify/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/docs': typeof DocsRouteWithChildren
  '/edit': typeof EditRoute
  '/governance': typeof GovernanceRoute
  '/issue': typeof IssueRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/reputation': typeof ReputationRoute
  '/resolve': typeof ResolveRoute
  '/rotate': typeof RotateRoute
  '/docs/cell-model': typeof DocsCellModelRoute
  '/docs/did-ckb': typeof DocsDidCkbRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/resolution': typeof DocsResolutionRoute
  '/verify/discord': typeof VerifyDiscordRoute
  '/verify/github': typeof VerifyGithubRoute
  '/docs/': typeof DocsIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/edit': typeof EditRoute
  '/governance': typeof GovernanceRoute
  '/issue': typeof IssueRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/reputation': typeof ReputationRoute
  '/resolve': typeof ResolveRoute
  '/rotate': typeof RotateRoute
  '/docs/cell-model': typeof DocsCellModelRoute
  '/docs/did-ckb': typeof DocsDidCkbRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/resolution': typeof DocsResolutionRoute
  '/verify/discord': typeof VerifyDiscordRoute
  '/verify/github': typeof VerifyGithubRoute
  '/docs': typeof DocsIndexRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/docs': typeof DocsRouteWithChildren
  '/edit': typeof EditRoute
  '/governance': typeof GovernanceRoute
  '/issue': typeof IssueRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/reputation': typeof ReputationRoute
  '/resolve': typeof ResolveRoute
  '/rotate': typeof RotateRoute
  '/docs/cell-model': typeof DocsCellModelRoute
  '/docs/did-ckb': typeof DocsDidCkbRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/resolution': typeof DocsResolutionRoute
  '/verify/discord': typeof VerifyDiscordRoute
  '/verify/github': typeof VerifyGithubRoute
  '/docs/': typeof DocsIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/claim'
    | '/deactivate'
    | '/docs'
    | '/edit'
    | '/governance'
    | '/issue'
    | '/migrate'
    | '/my'
    | '/reputation'
    | '/resolve'
    | '/rotate'
    | '/docs/cell-model'
    | '/docs/did-ckb'
    | '/docs/migration'
    | '/docs/resolution'
    | '/verify/discord'
    | '/verify/github'
    | '/docs/'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/claim'
    | '/deactivate'
    | '/edit'
    | '/governance'
    | '/issue'
    | '/migrate'
    | '/my'
    | '/reputation'
    | '/resolve'
    | '/rotate'
    | '/docs/cell-model'
    | '/docs/did-ckb'
    | '/docs/migration'
    | '/docs/resolution'
    | '/verify/discord'
    | '/verify/github'
    | '/docs'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/claim'
    | '/deactivate'
    | '/docs'
    | '/edit'
    | '/governance'
    | '/issue'
    | '/migrate'
    | '/my'
    | '/reputation'
    | '/resolve'
    | '/rotate'
    | '/docs/cell-model'
    | '/docs/did-ckb'
    | '/docs/migration'
    | '/docs/resolution'
    | '/verify/discord'
    | '/verify/github'
    | '/docs/'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ClaimRoute: typeof ClaimRoute
  DeactivateRoute: typeof DeactivateRoute
  DocsRoute: typeof DocsRouteWithChildren
  EditRoute: typeof EditRoute
  GovernanceRoute: typeof GovernanceRoute
  IssueRoute: typeof IssueRoute
  MigrateRoute: typeof MigrateRoute
  MyRoute: typeof MyRoute
  ReputationRoute: typeof ReputationRoute
  ResolveRoute: typeof ResolveRoute
  RotateRoute: typeof RotateRoute
  VerifyDiscordRoute: typeof VerifyDiscordRoute
  VerifyGithubRoute: typeof VerifyGithubRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deactivate': {
      id: '/deactivate'
      path: '/deactivate'
      fullPath: '/deactivate'
      preLoaderRoute: typeof DeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue': {
      id: '/issue'
      path: '/issue'
      fullPath: '/issue'
      preLoaderRoute: typeof IssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate': {
      id: '/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof MigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reputation': {
      id: '/reputation'
      path: '/reputation'
      fullPath: '/reputation'
      preLoaderRoute: typeof ReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolve': {
      id: '/resolve'
      path: '/resolve'
      fullPath: '/resolve'
      preLoaderRoute: typeof ResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate': {
      id: '/rotate'
      path: '/rotate'
      fullPath: '/rotate'
      preLoaderRoute: typeof RotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cell-model': {
      id: '/docs/cell-model'
      path: '/cell-model'
      fullPath: '/docs/cell-model'
      preLoaderRoute: typeof DocsCellModelRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/did-ckb': {
      id: '/docs/did-ckb'
      path: '/did-ckb'
      fullPath: '/docs/did-ckb'
      preLoaderRoute: typeof DocsDidCkbRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/migration': {
      id: '/docs/migration'
      path: '/migration'
      fullPath: '/docs/migration'
      preLoaderRoute: typeof DocsMigrationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resolution': {
      id: '/docs/resolution'
      path: '/resolution'
      fullPath: '/docs/resolution'
      preLoaderRoute: typeof DocsResolutionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/discord': {
      id: '/verify/discord'
      path: '/verify/discord'
      fullPath: '/verify/discord'
      preLoaderRoute: typeof VerifyDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/github': {
      id: '/verify/github'
      path: '/verify/github'
      fullPath: '/verify/github'
      preLoaderRoute: typeof VerifyGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsCellModelRoute: typeof DocsCellModelRoute
  DocsDidCkbRoute: typeof DocsDidCkbRoute
  DocsMigrationRoute: typeof DocsMigrationRoute
  DocsResolutionRoute: typeof DocsResolutionRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCellModelRoute: DocsCellModelRoute,
  DocsDidCkbRoute: DocsDidCkbRoute,
  DocsMigrationRoute: DocsMigrationRoute,
  DocsResolutionRoute: DocsResolutionRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ClaimRoute: ClaimRoute,
  DeactivateRoute: DeactivateRoute,
  DocsRoute: DocsRouteWithChildren,
  EditRoute: EditRoute,
  GovernanceRoute: GovernanceRoute,
  IssueRoute: IssueRoute,
  MigrateRoute: MigrateRoute,
  MyRoute: MyRoute,
  ReputationRoute: ReputationRoute,
  ResolveRoute: ResolveRoute,
  RotateRoute: RotateRoute,
  VerifyDiscordRoute: VerifyDiscordRoute,
  VerifyGithubRoute: VerifyGithubRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
