/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RotateRouteImport } from './routes/rotate'
import { Route as ResolveRouteImport } from './routes/resolve'
import { Route as MyRouteImport } from './routes/my'
import { Route as MigrateRouteImport } from './routes/migrate'
import { Route as EditRouteImport } from './routes/edit'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DeactivateRouteImport } from './routes/deactivate'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsResolutionRouteImport } from './routes/docs/resolution'
import { Route as DocsMigrationRouteImport } from './routes/docs/migration'
import { Route as DocsDidCkbRouteImport } from './routes/docs/did-ckb'
import { Route as DocsCellModelRouteImport } from './routes/docs/cell-model'

const RotateRoute = RotateRouteImport.update({
  id: '/rotate',
  path: '/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolveRoute = ResolveRouteImport.update({
  id: '/resolve',
  path: '/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateRoute = MigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeactivateRoute = DeactivateRouteImport.update({
  id: '/deactivate',
  path: '/deactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsResolutionRoute = DocsResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMigrationRoute = DocsMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDidCkbRoute = DocsDidCkbRouteImport.update({
  id: '/did-ckb',
  path: '/did-ckb',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCellModelRoute = DocsCellModelRouteImport.update({
  id: '/cell-model',
  path: '/cell-model',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/docs': typeof DocsRouteWithChildren
  '/edit': typeof EditRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/resolve': typeof ResolveRoute
  '/rotate': typeof RotateRoute
  '/docs/cell-model': typeof DocsCellModelRoute
  '/docs/did-ckb': typeof DocsDidCkbRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/resolution': typeof DocsResolutionRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/edit': typeof EditRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/resolve': typeof ResolveRoute
  '/rotate': typeof RotateRoute
  '/docs/cell-model': typeof DocsCellModelRoute
  '/docs/did-ckb': typeof DocsDidCkbRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/resolution': typeof DocsResolutionRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/deactivate': typeof DeactivateRoute
  '/docs': typeof DocsRouteWithChildren
  '/edit': typeof EditRoute
  '/migrate': typeof MigrateRoute
  '/my': typeof MyRoute
  '/resolve': typeof ResolveRoute
  '/rotate': typeof RotateRoute
  '/docs/cell-model': typeof DocsCellModelRoute
  '/docs/did-ckb': typeof DocsDidCkbRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/resolution': typeof DocsResolutionRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/deactivate'
    | '/docs'
    | '/edit'
    | '/migrate'
    | '/my'
    | '/resolve'
    | '/rotate'
    | '/docs/cell-model'
    | '/docs/did-ckb'
    | '/docs/migration'
    | '/docs/resolution'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/deactivate'
    | '/edit'
    | '/migrate'
    | '/my'
    | '/resolve'
    | '/rotate'
    | '/docs/cell-model'
    | '/docs/did-ckb'
    | '/docs/migration'
    | '/docs/resolution'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/deactivate'
    | '/docs'
    | '/edit'
    | '/migrate'
    | '/my'
    | '/resolve'
    | '/rotate'
    | '/docs/cell-model'
    | '/docs/did-ckb'
    | '/docs/migration'
    | '/docs/resolution'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  DeactivateRoute: typeof DeactivateRoute
  DocsRoute: typeof DocsRouteWithChildren
  EditRoute: typeof EditRoute
  MigrateRoute: typeof MigrateRoute
  MyRoute: typeof MyRoute
  ResolveRoute: typeof ResolveRoute
  RotateRoute: typeof RotateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rotate': {
      id: '/rotate'
      path: '/rotate'
      fullPath: '/rotate'
      preLoaderRoute: typeof RotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolve': {
      id: '/resolve'
      path: '/resolve'
      fullPath: '/resolve'
      preLoaderRoute: typeof ResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate': {
      id: '/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof MigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deactivate': {
      id: '/deactivate'
      path: '/deactivate'
      fullPath: '/deactivate'
      preLoaderRoute: typeof DeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/resolution': {
      id: '/docs/resolution'
      path: '/resolution'
      fullPath: '/docs/resolution'
      preLoaderRoute: typeof DocsResolutionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/migration': {
      id: '/docs/migration'
      path: '/migration'
      fullPath: '/docs/migration'
      preLoaderRoute: typeof DocsMigrationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/did-ckb': {
      id: '/docs/did-ckb'
      path: '/did-ckb'
      fullPath: '/docs/did-ckb'
      preLoaderRoute: typeof DocsDidCkbRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cell-model': {
      id: '/docs/cell-model'
      path: '/cell-model'
      fullPath: '/docs/cell-model'
      preLoaderRoute: typeof DocsCellModelRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsCellModelRoute: typeof DocsCellModelRoute
  DocsDidCkbRoute: typeof DocsDidCkbRoute
  DocsMigrationRoute: typeof DocsMigrationRoute
  DocsResolutionRoute: typeof DocsResolutionRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCellModelRoute: DocsCellModelRoute,
  DocsDidCkbRoute: DocsDidCkbRoute,
  DocsMigrationRoute: DocsMigrationRoute,
  DocsResolutionRoute: DocsResolutionRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  DeactivateRoute: DeactivateRoute,
  DocsRoute: DocsRouteWithChildren,
  EditRoute: EditRoute,
  MigrateRoute: MigrateRoute,
  MyRoute: MyRoute,
  ResolveRoute: ResolveRoute,
  RotateRoute: RotateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
